---
- name: Deploy Spring PetClinic
  hosts: production
  become: yes
  vars:
    app_name: spring-petclinic
    container_name: spring-petclinic
    container_port: 8080
    host_port: 80
    
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes
    
    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present
    
    - name: Create app directory
      file:
        path: "/opt/{{ app_name }}"
        state: directory
        mode: '0755'
    
    - name: Copy JAR file to server
      copy:
        src: "../target/spring-petclinic-{{ lookup('env', 'BUILD_NUMBER') }}.jar"
        dest: "/opt/{{ app_name }}/spring-petclinic.jar"
        mode: '0644'
    
    - name: Create docker-compose.yml
      copy:
        content: |
          version: '3'
          services:
            spring-petclinic:
              container_name: {{ container_name }}
              image: openjdk:11-jre-slim
              volumes:
                - /opt/{{ app_name }}/spring-petclinic.jar:/app.jar
              ports:
                - "{{ host_port }}:{{ container_port }}"
              command: ["java", "-jar", "/app.jar"]
        dest: "/opt/{{ app_name }}/docker-compose.yml"
    
    - name: Stop existing container
      shell: cd /opt/{{ app_name }} && docker-compose down
      ignore_errors: yes
    
    - name: Start container
      shell: cd /opt/{{ app_name }} && docker-compose up -d