---
- name: Deploy Spring PetClinic
  hosts: production
  become: yes
  vars:
    app_name: spring-petclinic
    container_name: spring-petclinic
    container_port: 8080
    host_port: 80
    
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes
    
    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present
    
    - name: Create app directory
      file:
        path: "/opt/{{ app_name }}"
        state: directory
        mode: '0755'
    
    - name: Copy JAR file from local build
      copy:
        src: "../target/spring-petclinic-{{ build_number }}.jar"
        dest: "/opt/{{ app_name }}/spring-petclinic.jar"
        mode: '0644'
      ignore_errors: yes
    
    # Alternative if JAR file doesn't exist
    - name: Copy Docker image instead
      shell: docker save spring-petclinic:{{ build_number }} | ssh devop@172.16.104.136 "cat > /tmp/spring-petclinic.tar"
      delegate_to: localhost
      ignore_errors: yes
    
    - name: Load Docker image on remote
      shell: docker load -i /tmp/spring-petclinic.tar
      ignore_errors: yes
    
    - name: Create docker-compose.yml
      copy:
        content: |
          version: '3'
          services:
            spring-petclinic:
              container_name: {{ container_name }}
              image: spring-petclinic:{{ build_number }}
              ports:
                - "{{ host_port }}:{{ container_port }}"
        dest: "/opt/{{ app_name }}/docker-compose.yml"
    
    - name: Stop existing container
      shell: cd /opt/{{ app_name }} && docker-compose down
      ignore_errors: yes
    
    - name: Start container
      shell: cd /opt/{{ app_name }} && docker-compose up -d