---
- name: Deploy Spring PetClinic
  hosts: production
  become: yes
  vars:
    app_name: spring-petclinic
    host_port: 80
    
  tasks:
    - name: Install Docker
      apt:
        name: docker.io
        state: present
        update_cache: yes
    
    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present
    
    - name: Create app directory
      file:
        path: "/opt/{{ app_name }}"
        state: directory
        mode: '0755'
    
    - name: Create a simple deployment script
      copy:
        content: |
          #!/bin/bash
          docker run -d --name spring-petclinic -p 80:8080 eclipse-temurin:17-jdk-focal java -jar /app/spring-petclinic.jar
        dest: "/opt/{{ app_name }}/deploy.sh"
        mode: '0755'
    
    - name: Stop existing containers
      shell: docker ps -aq | xargs -r docker stop | xargs -r docker rm
      ignore_errors: yes
    
    - name: Pull base Java image
      shell: docker pull eclipse-temurin:17-jdk-focal
    
    - name: Run deployment script
      shell: cd /opt/{{ app_name }} && ./deploy.sh